### ISSUE TITLE
Crash when app goes in background

### ISSUE THREAD

**Issue by sanandrea** [Cheesebaron/SlidingUpPanel#8]
Hi I am getting this [exception](https://gist.github.com/sanandrea/6274117da03ddc3944fa22d7cd4c2b1e) when I press home button. [Xamarin](https://gist.github.com/sanandrea/4ee77da079c813a2c37e9029891ce09a) Version used for building. Older version of Android SDK work.

**Comment by Cheesebaron** [comment]
Just adding the error directly here:

```
10-05 15:38:45.910: E/mono-rt(17633): [ERROR] FATAL UNHANDLED EXCEPTION: System.MethodAccessException: Method `(wrapper dynamic-method) object:dynamic_callback_0 (intptr,intptr)' is inaccessible from method `Cheesebaron.SlidingUpPanel.SlidingUpPanelLayout/SavedState:InitializeCreator ()'
```

Thanks for reporting this. Will have a look at it soon.

**Comment by emmanuele-villa** [comment]
Hi, any news about this crash? Can you reproduce it?
